### ISSUE TITLE
no error when checking for ws.Server

### ISSUE THREAD

**Issue by galambalazs** [indexzero/node-portfinder#15]
Creating a WebSocket server on a port and portfinder will still return it as available. 

https://github.com/websockets/ws

     var ws = require('ws');
     var server = new ws.Server({
        port: port
     });

**Comment by hbetts** [comment]
@galambalazs is this issue possibly the same as #9 and #13 ?

**Comment by eriktrom** [comment]
If this was related to #9 and #13 then it's been fixed completely on master. 

If it's related to finding an open socket and not find a port for a http host, then let me know to re-open. 

(context: port finder is mainly used for finding an open port, but *can* find an open socket (fd), code paths are completely separate, a web socket socket is an upgrade from a normal http server, so assuming all such things are true, closing! Fixed) :)
