### ISSUE TITLE
Provide a Promise-based API

### ISSUE THREAD

**Issue by justinfagnani** [indexzero/node-portfinder#17]
This would make portfinder compose with other Promise APIs as well as work nicely with async/await.

**Comment by hbetts** [comment]
I second the request :+1:

**Comment by indexzero** [comment]
No. Feel free to wrap this in another library for promises.

**Comment by indexzero** [comment]
Also: happy to link to your wrapped in `README.md` if you write it. Just open a PR for the doc change :+1:
