### ISSUE TITLE
1.0.1 breaks with EADDRNOTAVAIL

### ISSUE THREAD

**Issue by jeffcharles** [indexzero/node-portfinder#26]
On updating to 1.0.1 of portfinder, I started getting the following error:

```
{ [Error: listen EADDRNOTAVAIL ::1:8000]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '::1',
  port: 8000 }
```

Reverting to 1.0.0 fixes the issue.

**Comment by eriktrom** [comment]
@jeffcharles - thanks for reporting that, that'll save some time when i fix the remaining bugs in 1.0

**Comment by winfinit** [comment]
@eriktrom this one is pretty interesting... so we run into this exception when interface doesnt have ipv6 enabled... so we could add simple exception in a testPort to handle it, however "handling" becomes a bit opinionated, so for example, i would like to get a port for a host "::1", and interface is not enabled, i could report port is open (because ipv4 interfaces succeeded, and "EADDRNOTAVAIL" is ignored), however that is probably not what is expected... 

so what i am proposing is this: lets check if host is passed, and if host is an ip address, we check what type of ip it is, if it is ipv6, then we leave this exception as is, however if host is not passed, then we will ignore ::1 "EADDRNOTAVAIL", and report port as open.

what do you think?

**Comment by winfinit** [comment]
@eriktrom actually another option is add a setting that will ignore ipv6 errors, or pop ::1 off of hosts array...

here is a version without extra option:

in getPort we could have this:
```javascript
  var hosts = ['::1', '127.0.0.1', '0.0.0.0'];
  if (options.host) {
    hosts.push(options.host);
    var addr = ipaddr.parse(options.host);
    if (ipaddr.isValid) {
        if (ipaddr.kind() === "ipv4") {
            internals.ignoreIPv6Error = true;
        }
    }
  }
```

and in testPort in onError add this:
```javascript
if (internals.ignoreIPv6Error === true && err.code === 'EADDRNOTAVAIL') {
        return callback(null, options.port);
}
```

**Comment by eriktrom** [comment]
@winfinit - yes i agree - pop off the bad ones - related https://github.com/indexzero/node-portfinder/issues/26

**Comment by eriktrom** [comment]
however checking for ipv6 is no longer sufficient - we should just handle the error when it arrises, remove  from the array the bad interface, keep moving - although this does depend on the error code so, now we have 2 known bad cases as of #28 - perhaps a lookup table will follow but inlining this as a case statement until we get a third case seems fine. (if there are more we'll want to make the iterator a bit more legible i think)

**Comment by eriktrom** [comment]
3rd times the charm - your right - we can eliminate a whole class of bugs by checking for ipv6 first - then handle special cases after that (which are very possible - i have tried a few, although perhaps the users system settings become the responsible party in most cases after ipv6 is handled)

**Comment by stefanpenner** [comment]
Some systems don't support ipv6 yet either(thought that was worth mentioning)

**Comment by eriktrom** [comment]
Kool. So the consensus seems to be check for IPv6 support first. I'll throw together a pr assuming no one has any objections.

**Comment by indexzero** [comment]
@eriktom sounds good.

**Comment by dciccale** [comment]
just for the record, this happened to me because of being connected to a vpn.. not exactly know why, i guess it blocks that host

**Comment by eriktrom** [comment]
@dciccale - this should be fixed on 1.0.8. (Has been for some time).  Are u still seeing this issue behind a vpn?

**Comment by dciccale** [comment]
yes, with vpn connected i see the error, i disconnect the vpn and everything's fine. haven't dig in too much though. i'm using latest mockgoose which uses latest portfinder. the error is catched  here https://github.com/indexzero/node-portfinder/blob/master/lib/portfinder.js#L152

**Comment by eriktrom** [comment]
@dciccale - thanks for bringing this up. I'll take a look at mockgoose and probably ping u back for more info.

**Comment by dciccale** [comment]
@eriktrom with new version 1.0.9 which is a rollback it works

**Comment by eriktrom** [comment]
@dciccale - awesome thanks for verifying that!
