### ISSUE TITLE
can we get a release?

### ISSUE THREAD

**Issue by stefanpenner** [indexzero/node-portfinder#31]
would love to get @eriktrom's latest and greatest out in the wild: https://github.com/ember-cli/ember-cli/pull/5391/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L105

**Comment by eriktrom** [comment]
@indexzero - ping! :+1: lol

**Comment by indexzero** [comment]
Hey folks – I'm on vacation from 3/17-3/28. Will try to get a moment in front of the laptop :smiling_imp:

**Comment by indexzero** [comment]
Had good enough service in the car. Done as `1.0.3`. Thanks for the contributions everyone :100:

**Comment by stefanpenner** [comment]
Sweet thanks!

**Comment by eriktrom** [comment]
yep thanks (stef - I will update accordingly)
