### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by adi518** [indexzero/node-portfinder#32]
I'm trying to run multiple instances of Express and while one receives port 80 (defined as base-port) the other (I'm testing with just two instances atm) also receives 80 from portfinder (despite already taken). Bug or am I doing something wrong?

**Comment by eriktrom** [comment]
port 80 (or any port can be opened on more than one interface/host. If you have ipv6 enabled for example, you can start a server on port 80 on 127.0.0.1 and 0.0.0.0 and `::1` for example. There are possibly more interfaces via ipv6 that can also start, that we don't currently look for. One of those is `::0` something we discussed in an old ticket last week but should be moved here

can you run this once get those servers up on port 80, it'll give us more info

```sh
netstat -an | grep 80
```

Thanks

I'll help you work through this tomorrow(I have an emergency to fix today, server went down), in the meantime there is discussion of a similar issue at the end of https://github.com/indexzero/node-portfinder/issues/21 which we should move to this new ticket - but it provides context on your issue - try working through the steps mentioned there (which are basically running netstat)

**Comment by adi518** [comment]
I don't have ipv6 enabled, but I'll check again. I left a commented portfinder snippet in my code and tried open-port instead, which worked as expected. You'll have my feedback nonetheless.

**Comment by eriktrom** [comment]
Awesome thanks @adi518 - my guess is netstat should say the host is something other than 127.0.0.1, 0.0.0.0 or `::1` - and depending on what you get back when running that, we can add it to the list of hosts we check when trying to find an open port (on a unique host) - parallels VM uses port `::0` for example, which I plan on adding - your corporate issued laptop may also be setup with a network card that tries to do something non standard - we'll get it worked out, thanks a bunch for the help

**Comment by adi518** [comment]
I assumed something is missing from your checks. I'll let you know tomorrow.

**Comment by eriktrom** [comment]
kewl - also worth noting is that you can pass one additional host that we'll check via `portfinder.getPort({ host: 'myhostnameorip' })` which if that works we can make a default

**Comment by adi518** [comment]
Ah, that's good to know. I'll try it.

**Comment by adi518** [comment]
Didn't manage to play around with it today, hopefully in the next days. Thanks for your help.

**Comment by eriktrom** [comment]
@adi518 - this should be fixed by #33 - if you find otherwise, let me know. 

Thanks for filing the issue 👍

**Comment by adi518** [comment]
Great news, thanks. :)
