### ISSUE TITLE
It simply doesn't work for me. it always give me 800.

### ISSUE THREAD

**Issue by dharmax** [indexzero/node-portfinder#38]
However, this simple code does work:
`
export function findFreePort() {
    return new Promise((resolve, reject) => {
        var server = createServer()
            , port = 0
        server.on("listening", function () {
            port = server.address().port
            server.close()
        })
        server.on("close", function () {
            resolve(port)
        })
        server.on('error', function (err) {
            reject(err)
        })
        server.listen(0, '127.0.0.1')
    })
}
`

**Comment by eriktrom** [comment]
closing - superseded by #39
