### ISSUE TITLE
v1.0.8 defaultHosts not finding 0.0.0.0

### ISSUE THREAD

**Issue by PjEdwards** [indexzero/node-portfinder#43]
Somewhat recently `npm install portfinder` started giving us a version 1.0.8 (which strangely doesn't exist here on the github site). We're using it as part of ember-cli. When we spin up a server locally with portfinder debugging turned on we can see:

`portfinder:defaultHosts exports._defaultHosts is: ['::1', '127.0.0.1', <public_ip>, <vpn_ip> ]` 

Where it used to be: 

` portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '::1', '127.0.0.1', <public_ip>, <vpn_ip>]`

The omission is causing ember to try and serve the app on the `ip_address:port` instead of at `localhost:port` which, due to VPN stuff, isn't working.

Is this a deliberate omission?

**Comment by JasonGoemaat** [comment]
Bump!  Uncaught exception when trying on windows 10 using angular-cli.  The error is attempting to bind to the port on an adapter that isn't working or isn't allowed.

**Comment by eriktrom** [comment]
Sorry folks. I'll fix this as soon as I get off this airplane. I apologize.

**Comment by kabirsikand** [comment]
https://github.com/ember-cli/ember-cli/issues/6361 for reference.

**Comment by eriktrom** [comment]
portfinder has been reverted to 1.0.7 code and published to npm as 1.0.9

I fix the root cause in 1.10.0

Thanks to all who reported the issue
