### ISSUE TITLE
Expose testPort to public

### ISSUE THREAD

**Issue by GabrielDelepine** [indexzero/node-portfinder#54]
Hi @indexzero and thanks for the great job !

It would be nice to `export testPort`.

Why ?
I'am using node-portfinder to start a _web server_. I'd like to use `testPort` to regulary check if the port is in use to know when the _web server_ is up.

It would be much nicer to listen for a specific signal of the child process, but all web server does not implement it.

If you like the idea, I can make a PR

**Comment by eriktrom** [comment]
let me know if this is still a feature request, closing cause its stale (probably my fault, 1.5 years ago, sorry)
