### ISSUE TITLE
Request release sources on github also

### ISSUE THREAD

**Issue by pnemade** [indexzero/node-portfinder#55]
tarballs uploaded in npmjs does not contain any tests directory and I need them for Fedora packaging. Therefore I generally pick tarballs from github only. This project does not contain any recent tarballs. 

Can you please release the recent release tarball?

**Comment by eriktrom** [comment]
@pnemade - no problem - https://github.com/indexzero/node-portfinder/releases/tag/v1.0.13

does that do it, let me know (this wasn't made till just now, so from npm, it may try to pull master - also note the files in the tarball may still only include lib - https://github.com/indexzero/node-portfinder/blob/master/package.json#L15-L17

throw me a comment if this doesn't work for u (thinking it may not, but was easiest to try first)

**Comment by pnemade** [comment]
Thank you, that worked for me.

**Comment by eriktrom** [comment]
Np
