### ISSUE TITLE
May I use port range on finding port?

### ISSUE THREAD

**Issue by YounGoat** [indexzero/node-portfinder#59]
Something like port range syntax supported by [portman](https://www.npmjs.com/package/portman#portmanportrange).

**Comment by eriktrom** [comment]
This idea is certainly legit - the issue is the complexity it'll add - if you'd like to spike an implementation i'd be more than willing to help this become a thing...

**Comment by eriktrom** [comment]
@YounGoat - #63 allows a start and stop port option (see that pr for the correct named params to use, i'll make a ticket to create some very needed docs)

ps - didn't take a look at portman, but if the api fits with the code in #63, or your request invites further discussion, i'm be open to it
