### ISSUE TITLE
Option to provide a blacklist of ports while finding available port.

### ISSUE THREAD

**Issue by Prithvirajbilla** [indexzero/node-portfinder#61]
I am running into scenario where it would be nice to have a blacklist of ports (which should not be returned by portfinder, even if there are available). 

I am not sure how to achieve  this.

Let me know what you think of adding this option to the current api. 

happy to submit a PR.

**Comment by eriktrom** [comment]
This is similar to #59 where someone wanted to supply a range of ports - the way it works is you can pass a port (and host, or not) and it'll iterate until it finds a port that is open and won't bind to ipv6 while that port is already bound to ipv4 (loopback for both).

tl;dr - we could provide a stop port in this area of the code https://github.com/indexzero/node-portfinder/blob/master/lib/portfinder.js#L162-L163 - thus the options param would be `{ host?: number, port?: number, stopPort?: number }`, atm they are just `{ host?: number, port?: number }` both are optional, as there is a configurable `exports.basePort` that can be set. 

worth noting that this lib does not have a cli interface, just a function interface, so the line above would be the only real change needed. `if (options.stopPort >= options.port` before the next iteration, exit with a message... 

give it a shot, let me know. I know the code is hairy, sorry i inherited this project and did not realize how much the host would play a key role. a stop port though, won't affect that code and thus is a reasonable feature to bring in.

**Comment by Prithvirajbilla** [comment]
Thanks for your reply. 

I will take a shot at this. I think I should I have something by EOW.
