### ISSUE TITLE
can i disable the options.startPort >1024 check?

### ISSUE THREAD

**Issue by leekafai** [indexzero/node-portfinder#65]
when i developing front end pages,i usually set webpack dev port to 80,with hosting 127.0.0.1:80 to a fake 
domain,because some modules need to validate the domain name ,such as login module,so i think it would be more easy to use if this '1024' check can be disabled or default disabled.
Still thanks for this awesome module.

**Comment by Adam-Michalski** [comment]
I have the same problem when using AngularCli.
When app starts on port 80 I cannot run this even with administrator privileges.
Error: 
`Provided options.startPort(80) is less than 1024, which are cannot be bound.`

**Comment by eriktrom** [comment]
@leekafai @Adam-Michalski - make a pr to change the line above this comment to probably < 0 - i'll do it around lunch if u don't get to it 

we released that yesterday, sorry `bout that, have it cleaned up here in a sec

**Comment by eriktrom** [comment]
fixed and published - let me know of further issues, thanks
